name: Docker Build/Publish Image
on:
  push:
    tags:
    - "*"
  schedule:
  - cron:  '15 6 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    uses: sfudeus/workflows/.github/workflows/docker-build-publish-main.yaml@main
    secrets: inherit
